'use client'
import Link from 'next/link'
import {motion,MotionConfig} from 'motion/react'
import {useEffect,useState} from 'react'
import {getCatalog,Product} from '../lib/api'

const samples=[['01','Tela PVC','Color que aguanta la calle.'],['02','Adhesivos','Superficies que piden atención.'],['03','Palomas','Presencia a la altura de tu negocio.'],['04','Impresión digital','Una idea, muchas escalas.']]
export default function Home(){const [products,setProducts]=useState<Product[]>([]);const [open,setOpen]=useState<number|null>(null);const [menu,setMenu]=useState(false)
 useEffect(()=>{getCatalog().then(x=>setProducts(x.products.filter(p=>p.active))).catch(()=>{})},[])
 return <MotionConfig reducedMotion="user"><main>
  <header className="fixed top-0 z-50 w-full border-b border-[#18244a1c] bg-[#FAFAF7eF] backdrop-blur-md"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 md:px-10"><Link href="/" className="display text-2xl tracking-tight">Mega<span className="text-[#EF3785]">Colours</span><span className="text-[#00A9D6]">.</span></Link><button aria-label="Abrir menú" onClick={()=>setMenu(!menu)} className="focus-ring md:hidden text-2xl">☰</button><nav className={`${menu?'flex':'hidden'} absolute left-0 top-full w-full flex-col gap-5 border-b border-[#18244a1c] bg-[#FAFAF7] p-5 md:static md:flex md:w-auto md:flex-row md:items-center md:border-0 md:bg-transparent md:p-0`}><a className="focus-ring text-sm" href="#servicios" onClick={()=>setMenu(false)}>Servicios</a><a className="focus-ring text-sm" href="#proceso" onClick={()=>setMenu(false)}>Cómo funciona</a><a className="focus-ring text-sm" href="#preguntas" onClick={()=>setMenu(false)}>Preguntas</a><Link className="focus-ring rounded-full bg-[#18244A] px-5 py-3 text-center text-sm font-bold text-white transition hover:bg-[#EF3785]" href="/cotizar">Cotizar ahora</Link></nav></div></header>
  <section className="grid-paper relative overflow-hidden px-5 pb-20 pt-36 md:px-10 md:pb-28 md:pt-48"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><div><p className="mb-6 text-xs font-bold uppercase tracking-[.25em] text-[#EF3785]">Imprenta · Santiago / Chile</p><h1 className="display max-w-3xl text-[clamp(4rem,10vw,9rem)] leading-[.82]">Haz que<br/><span className="text-[#00A9D6]">se note.</span></h1><p className="mt-8 max-w-lg text-lg leading-relaxed text-[#667089]">Impresión con carácter para negocios que quieren ocupar espacio. Configura, cotiza y dale forma a tu próxima idea.</p><Link href="/cotizar" className="focus-ring mt-9 inline-flex items-center gap-3 rounded-full bg-[#EF3785] px-7 py-4 font-bold text-white transition hover:-translate-y-1">Empieza a cotizar <span aria-hidden>↗</span></Link></div><motion.div initial={{opacity:0,scale:.95}} animate={{opacity:1,scale:1}} transition={{duration:.7}} className="relative mx-auto h-[390px] w-full max-w-[530px] sm:h-[500px]"><div className="absolute left-[8%] top-[12%] h-[68%] w-[73%] rotate-[-10deg] border border-[#18244a44] bg-white p-6 shadow-[12px_18px_0_#FFE04B] sm:p-10"><div className="h-full border-2 border-dashed border-[#00A9D6] p-4 sm:p-7"><p className="display text-5xl leading-none sm:text-7xl">Tu<br/><span className="text-[#00A9D6]">marca</span><br/>aquí<span className="text-[#EF3785]">.</span></p><div className="mt-8 h-3 w-2/3 bg-[#18244A]"/><div className="mt-3 h-3 w-1/2 bg-[#EF3785]"/></div></div><div className="absolute bottom-[4%] right-[1%] h-[60%] w-[64%] rotate-[8deg] border border-[#18244a44] bg-[#00A9D6] p-5 shadow-[-12px_16px_0_#EF3785] sm:p-8"><div className="flex h-full flex-col justify-between border-2 border-[#FAFAF7aa] p-4 sm:p-6"><span className="text-xs font-bold uppercase tracking-[.2em] text-white">Muestra de composición</span><div><p className="display text-5xl leading-[.82] text-white sm:text-7xl">Color<br/>en<br/><span className="text-[#FFE04B]">movimiento</span></p><span className="mt-5 block text-xs font-bold text-white">CMYK / 001</span></div></div></div><span className="absolute left-0 top-0 font-mono text-xs">+ registro</span><span className="absolute bottom-2 right-0 font-mono text-xs">muestra / 2026</span></motion.div></div></section>
  <section id="servicios" className="mx-auto max-w-7xl px-5 py-24 md:px-10 md:py-32"><div className="mb-12 flex items-end justify-between gap-5"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.25em] text-[#00A9D6]">Lo que hacemos</p><h2 className="display text-5xl md:text-7xl">Piezas con<br/>propósito.</h2></div><span className="hidden max-w-xs text-right text-sm text-[#667089] md:block">Soluciones impresas pensadas para verse, durar y hacer avanzar tu negocio.</span></div><div className="grid gap-px overflow-hidden border border-[#18244a22] bg-[#18244a22] sm:grid-cols-2 lg:grid-cols-4">{(products.length?products.map((p,i)=>[String(i+1).padStart(2,'0'),p.name,p.description]):samples).map((s,i)=><article key={s[0]} className="group bg-[#FAFAF7] p-6 transition hover:bg-[#FFE04B] md:p-8"><span className="font-mono text-xs text-[#667089]">{s[0]}</span><div className="my-16 h-20 w-full transition group-hover:translate-x-2" style={{background:i%3===0?'#00A9D6':i%3===1?'#EF3785':'#18244A',clipPath:i%2?'polygon(0 12%,100% 0,88% 100%,5% 86%)':'polygon(6% 0,100% 14%,92% 100%,0 86%)'}}/><h3 className="display text-3xl">{s[1]}</h3><p className="mt-3 text-sm leading-relaxed text-[#667089]">{s[2]}</p></article>)}</div><p className="mt-4 text-xs text-[#667089]">Catálogo conectado a disponibilidad en tiempo real.</p></section>
  <section className="bg-[#18244A] px-5 py-24 text-white md:px-10 md:py-32"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.25em] text-[#FFE04B]">Aplicaciones de muestra</p><h2 className="display text-5xl leading-[.9] md:text-7xl">Imagina<br/>el siguiente<br/><span className="text-[#EF3785]">formato.</span></h2></div><div className="grid grid-cols-2 gap-3 sm:gap-5">{samples.map((s,i)=><div key={s[0]} className="border border-white/20 p-4 sm:p-6"><div className="mb-8 aspect-[4/3]" style={{background:[ '#EF3785','#FFE04B','#00A9D6','#FAFAF7'][i]}}/><span className="font-mono text-xs text-white/60">{s[0]} / muestra conceptual</span><h3 className="mt-2 text-lg font-bold">{s[1]}</h3></div>)}</div></div></section>
  <section id="proceso" className="mx-auto max-w-7xl px-5 py-24 md:px-10 md:py-32"><p className="mb-3 text-xs font-bold uppercase tracking-[.25em] text-[#EF3785]">El proceso</p><h2 className="display mb-14 text-5xl md:text-7xl">Del píxel<br/>al espacio.</h2><div className="grid gap-10 md:grid-cols-3">{[['01','Cuéntanos la idea','Elige tu producto y arma una configuración que calce con lo que necesitas.'],['02','Ajustamos contigo','Revisamos el archivo, el formato y los detalles que hacen la diferencia.'],['03','Lo hacemos visible','Recibes una pieza lista para instalar, compartir o poner en circulación.']].map(x=><div key={x[0]} className="border-t-2 border-[#18244A] pt-5"><span className="display text-4xl text-[#00A9D6]">{x[0]}</span><h3 className="mt-8 text-xl font-bold">{x[1]}</h3><p className="mt-3 leading-relaxed text-[#667089]">{x[2]}</p></div>)}</div></section>
  <section className="bg-[#FFE04B] px-5 py-20 md:px-10 md:py-28"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 md:flex-row md:items-end"><div><p className="mb-3 text-xs font-bold uppercase tracking-[.25em]">Tu próximo soporte</p><h2 className="display max-w-3xl text-6xl leading-[.84] md:text-8xl">Hazlo<br/><span className="text-[#EF3785]">cotizable.</span></h2></div><Link href="/cotizar" className="focus-ring rounded-full bg-[#18244A] px-7 py-4 font-bold text-white transition hover:bg-[#EF3785]">Abrir cotizador ↗</Link></div></section>
  <section id="preguntas" className="mx-auto max-w-4xl px-5 py-24 md:py-32"><p className="mb-3 text-xs font-bold uppercase tracking-[.25em] text-[#00A9D6]">Antes de partir</p><h2 className="display mb-10 text-5xl md:text-7xl">Preguntas<br/>frecuentes.</h2>{[['¿Puedo pedir medidas especiales?','Sí. Cuando el producto lo permite, puedes ingresar ancho y alto dentro de los rangos indicados en el cotizador.'],['¿El precio que veo es definitivo?','La cotización se recalcula en el servidor al enviarla. El valor mostrado es una referencia para configurar tu pedido.'],['¿Qué archivo debo enviar?','Aceptamos imágenes JPEG, PNG y WebP. Puedes subirla durante el flujo y conservaremos el original para revisarlo.']].map((x,i)=><div key={x[0]} className="border-t border-[#18244a33] py-5"><button className="focus-ring flex w-full items-center justify-between text-left font-bold" onClick={()=>setOpen(open===i?null:i)}>{x[0]}<span className="text-2xl">{open===i?'−':'+'}</span></button>{open===i&&<p className="max-w-2xl pt-4 leading-relaxed text-[#667089]">{x[1]}</p>}</div>)}</section>
  <footer className="border-t border-[#18244a22] px-5 py-8 md:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 text-sm text-[#667089] sm:flex-row"><span className="display text-lg text-[#18244A]">Mega<span className="text-[#EF3785]">Colours</span>.</span><span>Impresión para ideas en movimiento.</span><span>© {new Date().getFullYear()} MegaColours</span></div></footer>
 </main></MotionConfig>
}
