import { test, expect } from '@playwright/test';

test('crea un producto y un formato desde administración', async ({ page, request }) => {
  await page.goto('/admin');
  await page.getByLabel('Correo electrónico', { exact: true }).fill('test-admin@megacolours.invalid');
  await page.getByLabel('Contraseña', { exact: true }).fill('Isolated-browser-test-password-2026!');
  await page.getByRole('button', { name: /Entrar al panel/ }).click();
  await page.getByRole('button', { name: /Nuevo producto/ }).click();
  const editor = page.getByRole('dialog');
  await editor.getByLabel('Nombre', { exact: true }).fill('Letrero de prueba');
  await editor.getByLabel('Slug', { exact: true }).fill('letrero-prueba');
  await editor.getByLabel('Categoría', { exact: true }).fill('Señalética');
  await editor.getByLabel('Precio por m²', { exact: true }).fill('15000');
  await editor.getByRole('button', { name: /Agregar/ }).first().click();
  await editor.getByLabel('Nombre del preajuste', { exact: true }).fill('Formato de prueba');
  await editor.getByLabel('Ancho', { exact: true }).fill('50');
  await editor.getByLabel('Alto', { exact: true }).fill('70');
  await editor.getByLabel('Precio del preajuste', { exact: true }).fill('9000');
  await editor.getByRole('button', { name: /Guardar producto/ }).click();
  await expect(editor).not.toBeVisible();
  await expect(page.getByRole('heading', { name: 'Letrero de prueba' })).toBeVisible();
  const catalog = await (await request.get('/api/catalog')).json();
  const product = catalog.products.find((p: { name: string }) => p.name === 'Letrero de prueba');
  expect(product).toBeTruthy();
  expect(product.presets[0]).toMatchObject({ name: 'Formato de prueba', width: 50, height: 70, fixedPrice: 9000 });
  await page.getByRole('button', { name: /Nuevo producto/ }).click();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button', { name: /Métodos de entrega/ }).click();
  await page.getByRole('button', { name: /Nueva entrega/ }).click();
  const deliveryEditor = page.getByRole('dialog');
  await deliveryEditor.getByLabel('Nombre', { exact: true }).fill('Entrega de prueba');
  await deliveryEditor.getByLabel('Precio', { exact: true }).fill('7000');
  await deliveryEditor.getByLabel('Requiere dirección', { exact: true }).check();
  await deliveryEditor.getByRole('button', { name: /Guardar método/ }).click();
  await expect(deliveryEditor).not.toBeVisible();
  const updated = await (await request.get('/api/catalog')).json();
  expect(updated.deliveryMethods.find((d: { name: string }) => d.name === 'Entrega de prueba')).toMatchObject({ price: 7000, requiresAddress: true, active: true });
});
